cargo-features = ["per-package-target"]

[package]
name = "jpeg-wasm"
version = "0.1.0"
edition = "2024"
forced-target = "wasm32-unknown-unknown"

[dependencies]
zune-jpeg = { version = "0.4.14", default-features = false }
